# Generated by Django 3.2.6 on 2023-04-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_country_donation_requestdonation_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestdonation',
            old_name='sountry',
            new_name='country',
        ),
    ]
